### ISSUE TITLE
updated image

### ISSUE THREAD

**Issue by mohitjoshi155** [huangzulin/rclone-aria2#1]
HI
can you please publish updated image of this in dockerhub?
Thanks

**Comment by huangzulin** [comment]
wait

**Comment by huangzulin** [comment]
recommend use this repo ,it is more powerfull. [[recommend](https://github.com/P3TERX/Aria2-Pro-Docker)](https://github.com/P3TERX/Aria2-Pro-Docker) @mohitjoshi155
